// Code generated by packages/contract/codegen/generate.py. DO NOT EDIT.
#![allow(clippy::derivable_impls)]

use std::collections::BTreeMap;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

pub const PROTOCOL_VERSION: u8 = 1;
pub const SCHEMA_ID: &str = "https://schemas.vodoge.cloud/edge-cloud/v1/edge-cloud.schema.json";
pub const WS_SUBPROTOCOL: &str = "vodoge.edge.v1";

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum MessageKind {
    Resume,
    ResumeAck,
    UplinkAck,
    UplinkGap,
    UplinkGapAck,
    Ping,
    Pong,
    CommandDeliver,
    CommandReceipt,
    SmsReceived,
    SmsStatusReport,
    DeviceState,
    CommandResult,
    EsimInventory,
    Alert,
    ProxyTraffic,
    ProtocolError,
}

impl MessageKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Resume => "Resume",
            Self::ResumeAck => "ResumeAck",
            Self::UplinkAck => "UplinkAck",
            Self::UplinkGap => "UplinkGap",
            Self::UplinkGapAck => "UplinkGapAck",
            Self::Ping => "Ping",
            Self::Pong => "Pong",
            Self::CommandDeliver => "CommandDeliver",
            Self::CommandReceipt => "CommandReceipt",
            Self::SmsReceived => "SmsReceived",
            Self::SmsStatusReport => "SmsStatusReport",
            Self::DeviceState => "DeviceState",
            Self::CommandResult => "CommandResult",
            Self::EsimInventory => "EsimInventory",
            Self::Alert => "Alert",
            Self::ProxyTraffic => "ProxyTraffic",
            Self::ProtocolError => "ProtocolError",
        }
    }

    pub fn is_sequenced(self) -> bool {
        match self {
            Self::Resume => false,
            Self::ResumeAck => false,
            Self::UplinkAck => false,
            Self::UplinkGap => false,
            Self::UplinkGapAck => false,
            Self::Ping => false,
            Self::Pong => false,
            Self::CommandDeliver => false,
            Self::CommandReceipt => false,
            Self::SmsReceived => true,
            Self::SmsStatusReport => true,
            Self::DeviceState => true,
            Self::CommandResult => true,
            Self::EsimInventory => true,
            Self::Alert => true,
            Self::ProxyTraffic => true,
            Self::ProtocolError => false,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContextValue {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<ContextValue>),
    Object(BTreeMap<String, ContextValue>),
}

mod u64_decimal {
    use super::*;
    pub fn serialize<S: Serializer>(value: &u64, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&value.to_string())
    }
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u64, D::Error> {
        let raw = String::deserialize(deserializer)?;
        raw.parse::<u64>().map_err(serde::de::Error::custom)
    }
}

mod opt_u64_decimal {
    use super::*;
    pub fn serialize<S: Serializer>(value: &Option<u64>, serializer: S) -> Result<S::Ok, S::Error> {
        match value {
            Some(v) => serializer.serialize_some(&v.to_string()),
            None => serializer.serialize_none(),
        }
    }
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Option<u64>, D::Error> {
        let raw = Option::<String>::deserialize(deserializer)?;
        raw.map(|value| value.parse::<u64>().map_err(serde::de::Error::custom)).transpose()
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SequenceRange {
    #[serde(rename = "from", with = "u64_decimal")]
    pub from: u64,
    #[serde(rename = "through", with = "u64_decimal")]
    pub through: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResumePayload {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "last_assigned_seq", with = "u64_decimal")]
    pub last_assigned_seq: u64,
    #[serde(rename = "lowest_retained_seq", default, skip_serializing_if = "Option::is_none", with = "opt_u64_decimal")]
    pub lowest_retained_seq: Option<u64>,
    #[serde(rename = "last_acked_seq", with = "u64_decimal")]
    pub last_acked_seq: u64,
    #[serde(rename = "pending_gap_ids")]
    pub pending_gap_ids: Vec<String>,
    #[serde(rename = "capability_matrix_version")]
    pub capability_matrix_version: String,
    #[serde(rename = "edge_version", default, skip_serializing_if = "Option::is_none")]
    pub edge_version: Option<String>,
    #[serde(rename = "queue_records", default, skip_serializing_if = "Option::is_none")]
    pub queue_records: Option<i64>,
    #[serde(rename = "queue_bytes", default, skip_serializing_if = "Option::is_none")]
    pub queue_bytes: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResumeAckPayload {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "committed_through", with = "u64_decimal")]
    pub committed_through: u64,
    #[serde(rename = "missing_ranges")]
    pub missing_ranges: Vec<SequenceRange>,
    #[serde(rename = "more_missing")]
    pub more_missing: bool,
    #[serde(rename = "max_in_flight")]
    pub max_in_flight: i64,
    #[serde(rename = "server_time")]
    pub server_time: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UplinkAckPayload {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "committed_through", with = "u64_decimal")]
    pub committed_through: u64,
    #[serde(rename = "missing_ranges")]
    pub missing_ranges: Vec<SequenceRange>,
    #[serde(rename = "more_missing")]
    pub more_missing: bool,
    #[serde(rename = "max_in_flight")]
    pub max_in_flight: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UplinkGapPayload {
    #[serde(rename = "gap_id")]
    pub gap_id: String,
    #[serde(rename = "ranges")]
    pub ranges: Vec<SequenceRange>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "dropped_records")]
    pub dropped_records: i64,
    #[serde(rename = "occurred_at")]
    pub occurred_at: i64,
    #[serde(rename = "drop_policy")]
    pub drop_policy: String,
    #[serde(rename = "detail", default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UplinkGapAckPayload {
    #[serde(rename = "gap_id")]
    pub gap_id: String,
    #[serde(rename = "accepted")]
    pub accepted: bool,
    #[serde(rename = "committed_through", with = "u64_decimal")]
    pub committed_through: u64,
    #[serde(rename = "reason_code", default, skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PingPayload {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "sent_at")]
    pub sent_at: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PongPayload {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "ping_id")]
    pub ping_id: String,
    #[serde(rename = "server_time")]
    pub server_time: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandDeliverPayload {
    #[serde(rename = "cmd_id")]
    pub cmd_id: String,
    #[serde(rename = "issued_at")]
    pub issued_at: i64,
    #[serde(rename = "expires_at")]
    pub expires_at: i64,
    #[serde(rename = "attempt", default, skip_serializing_if = "Option::is_none")]
    pub attempt: Option<i64>,
    #[serde(rename = "command")]
    pub command: Command,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandReceiptPayload {
    #[serde(rename = "cmd_id")]
    pub cmd_id: String,
    #[serde(rename = "delivery_id")]
    pub delivery_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "received_at")]
    pub received_at: i64,
    #[serde(rename = "retry_after_ms", default, skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<i64>,
    #[serde(rename = "reason_code", default, skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SmsReceivedPayload {
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "peer")]
    pub peer: String,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "received_at")]
    pub received_at: i64,
    #[serde(rename = "iccid")]
    pub iccid: String,
    #[serde(rename = "bearer")]
    pub bearer: String,
    #[serde(rename = "encoding")]
    pub encoding: String,
    #[serde(rename = "modem_storage_index", default, skip_serializing_if = "Option::is_none")]
    pub modem_storage_index: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SmsStatusReportPayload {
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "peer")]
    pub peer: String,
    #[serde(rename = "reference")]
    pub reference: i64,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "status_code", default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i64>,
    #[serde(rename = "reported_at")]
    pub reported_at: i64,
    #[serde(rename = "submitted_at", default, skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<i64>,
    #[serde(rename = "delivered_at", default, skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProxyTrafficPayload {
    #[serde(rename = "reported_at")]
    pub reported_at: i64,
    #[serde(rename = "instances")]
    pub instances: Vec<ProxyTrafficEntry>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProxyTrafficEntry {
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    #[serde(rename = "bytes_up")]
    pub bytes_up: i64,
    #[serde(rename = "bytes_down")]
    pub bytes_down: i64,
    #[serde(rename = "connections")]
    pub connections: i64,
    #[serde(rename = "errors", default, skip_serializing_if = "Option::is_none")]
    pub errors: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceStatePayload {
    #[serde(rename = "observed_at")]
    pub observed_at: i64,
    #[serde(rename = "modems")]
    pub modems: Vec<ModemState>,
    #[serde(rename = "host", default, skip_serializing_if = "Option::is_none")]
    pub host: Option<HostState>,
    #[serde(rename = "managed_imeis", default, skip_serializing_if = "Option::is_none")]
    pub managed_imeis: Option<Vec<String>>,
    #[serde(rename = "discoveries", default, skip_serializing_if = "Option::is_none")]
    pub discoveries: Option<Vec<DiscoveryCandidate>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostState {
    #[serde(rename = "public_ip", default, skip_serializing_if = "Option::is_none")]
    pub public_ip: Option<String>,
    #[serde(rename = "cpu_percent", default, skip_serializing_if = "Option::is_none")]
    pub cpu_percent: Option<f64>,
    #[serde(rename = "memory_used_bytes", default, skip_serializing_if = "Option::is_none")]
    pub memory_used_bytes: Option<i64>,
    #[serde(rename = "memory_total_bytes", default, skip_serializing_if = "Option::is_none")]
    pub memory_total_bytes: Option<i64>,
    #[serde(rename = "disk_used_bytes", default, skip_serializing_if = "Option::is_none")]
    pub disk_used_bytes: Option<i64>,
    #[serde(rename = "disk_total_bytes", default, skip_serializing_if = "Option::is_none")]
    pub disk_total_bytes: Option<i64>,
    #[serde(rename = "net_rx_bytes_per_sec", default, skip_serializing_if = "Option::is_none")]
    pub net_rx_bytes_per_sec: Option<i64>,
    #[serde(rename = "net_tx_bytes_per_sec", default, skip_serializing_if = "Option::is_none")]
    pub net_tx_bytes_per_sec: Option<i64>,
    #[serde(rename = "cpu_model", default, skip_serializing_if = "Option::is_none")]
    pub cpu_model: Option<String>,
    #[serde(rename = "kernel", default, skip_serializing_if = "Option::is_none")]
    pub kernel: Option<String>,
    #[serde(rename = "hostname", default, skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModemState {
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "registration")]
    pub registration: String,
    #[serde(rename = "iccid", default, skip_serializing_if = "Option::is_none")]
    pub iccid: Option<String>,
    #[serde(rename = "signal_dbm", default, skip_serializing_if = "Option::is_none")]
    pub signal_dbm: Option<i64>,
    #[serde(rename = "rsrp", default, skip_serializing_if = "Option::is_none")]
    pub rsrp: Option<i64>,
    #[serde(rename = "rsrq", default, skip_serializing_if = "Option::is_none")]
    pub rsrq: Option<i64>,
    #[serde(rename = "sinr", default, skip_serializing_if = "Option::is_none")]
    pub sinr: Option<i64>,
    #[serde(rename = "discovery", default, skip_serializing_if = "Option::is_none")]
    pub discovery: Option<String>,
    #[serde(rename = "manageable", default, skip_serializing_if = "Option::is_none")]
    pub manageable: Option<bool>,
    #[serde(rename = "family", default, skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    #[serde(rename = "imsi", default, skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    #[serde(rename = "home_plmn", default, skip_serializing_if = "Option::is_none")]
    pub home_plmn: Option<String>,
    #[serde(rename = "serving_plmn", default, skip_serializing_if = "Option::is_none")]
    pub serving_plmn: Option<String>,
    #[serde(rename = "firmware", default, skip_serializing_if = "Option::is_none")]
    pub firmware: Option<String>,
    #[serde(rename = "msisdn", default, skip_serializing_if = "Option::is_none")]
    pub msisdn: Option<String>,
    #[serde(rename = "control_port", default, skip_serializing_if = "Option::is_none")]
    pub control_port: Option<String>,
    #[serde(rename = "usb_device", default, skip_serializing_if = "Option::is_none")]
    pub usb_device: Option<String>,
    #[serde(rename = "apn_contexts", default, skip_serializing_if = "Option::is_none")]
    pub apn_contexts: Option<Vec<ApnContext>>,
    #[serde(rename = "adoption_note", default, skip_serializing_if = "Option::is_none")]
    pub adoption_note: Option<String>,
    #[serde(rename = "adopted_at", default, skip_serializing_if = "Option::is_none")]
    pub adopted_at: Option<i64>,
    #[serde(rename = "adopted_by", default, skip_serializing_if = "Option::is_none")]
    pub adopted_by: Option<String>,
    #[serde(rename = "capability")]
    pub capability: CapabilitySummary,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DiscoveryCandidate {
    #[serde(rename = "candidate_key")]
    pub candidate_key: String,
    #[serde(rename = "usb_device", default, skip_serializing_if = "Option::is_none")]
    pub usb_device: Option<String>,
    #[serde(rename = "transport")]
    pub transport: String,
    #[serde(rename = "control_port")]
    pub control_port: String,
    #[serde(rename = "vendor_id", default, skip_serializing_if = "Option::is_none")]
    pub vendor_id: Option<String>,
    #[serde(rename = "product_id", default, skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "imei", default, skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(rename = "detail", default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "last_seen", default, skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RenameEsimProfileCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "iccid")]
    pub iccid: String,
    #[serde(rename = "nickname", default, skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DisableEsimProfileCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "iccid")]
    pub iccid: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeleteEsimProfileCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "iccid")]
    pub iccid: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RegisterModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "note", default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CreateModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "family")]
    pub family: String,
    #[serde(rename = "note", default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UnregisterModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReconfirmModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "note", default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClaimModemCandidateCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "candidate_key")]
    pub candidate_key: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RevokeModemCandidateCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "candidate_key")]
    pub candidate_key: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReadLogsCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "after", default, skip_serializing_if = "Option::is_none")]
    pub after: Option<i64>,
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(rename = "contains", default, skip_serializing_if = "Option::is_none")]
    pub contains: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigureApnCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "cid")]
    pub cid: i64,
    #[serde(rename = "pdp_type", default, skip_serializing_if = "Option::is_none")]
    pub pdp_type: Option<String>,
    #[serde(rename = "apn")]
    pub apn: String,
    #[serde(rename = "username", default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "auth", default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ApnContext {
    #[serde(rename = "cid")]
    pub cid: i64,
    #[serde(rename = "pdp_type", default, skip_serializing_if = "Option::is_none")]
    pub pdp_type: Option<String>,
    #[serde(rename = "apn", default, skip_serializing_if = "Option::is_none")]
    pub apn: Option<String>,
    #[serde(rename = "username", default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "auth", default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    #[serde(rename = "has_password", default, skip_serializing_if = "Option::is_none")]
    pub has_password: Option<bool>,
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CapabilitySummary {
    #[serde(rename = "sms_mo")]
    pub sms_mo: String,
    #[serde(rename = "sms_mt")]
    pub sms_mt: String,
    #[serde(rename = "matrix_version")]
    pub matrix_version: String,
    #[serde(rename = "carrier_profile", default, skip_serializing_if = "Option::is_none")]
    pub carrier_profile: Option<String>,
    #[serde(rename = "origin", default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandResultPayload {
    #[serde(rename = "cmd_id")]
    pub cmd_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "completed_at")]
    pub completed_at: i64,
    #[serde(rename = "attempts")]
    pub attempts: i64,
    #[serde(rename = "reason_code", default, skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "details", default, skip_serializing_if = "Option::is_none")]
    pub details: Option<ContextValue>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EsimInventoryPayload {
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "eid")]
    pub eid: String,
    #[serde(rename = "collected_at")]
    pub collected_at: i64,
    #[serde(rename = "profiles")]
    pub profiles: Vec<EsimProfile>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EsimProfile {
    #[serde(rename = "iccid")]
    pub iccid: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "nickname", default, skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AlertPayload {
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "occurred_at")]
    pub occurred_at: i64,
    #[serde(rename = "context")]
    pub context: ContextValue,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SendSmsCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "modem_imei", default, skip_serializing_if = "Option::is_none")]
    pub modem_imei: Option<String>,
    #[serde(rename = "iccid", default, skip_serializing_if = "Option::is_none")]
    pub iccid: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RestartModemCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RunAtCommandCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "timeout_ms", default, skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<i64>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SendUssdCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "stage", default, skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SetRadioCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ScanOperatorsCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SelectOperatorCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "plmn", default, skip_serializing_if = "Option::is_none")]
    pub plmn: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModemReportCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResetModemUsbCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SetDataNetworkCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SetUsbnetModeCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "mode")]
    pub mode: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReregisterNetworkCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RefreshModemsCommand {
    #[serde(rename = "kind")]
    pub kind: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ListEsimProfilesCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReadEsimInfoCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RetrieveEsimNotificationCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "sequence_number")]
    pub sequence_number: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InitiateEsimAuthenticationCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "smdp_address", default, skip_serializing_if = "Option::is_none")]
    pub smdp_address: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DownloadEsimProfileCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "activation_code")]
    pub activation_code: String,
    #[serde(rename = "confirmation_code", default, skip_serializing_if = "Option::is_none")]
    pub confirmation_code: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigureProxyCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "instances")]
    pub instances: Vec<ProxyInstanceSpec>,
    #[serde(rename = "upstreams")]
    pub upstreams: Vec<ProxyUpstreamSpec>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProxyInstanceSpec {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "listen_addr")]
    pub listen_addr: String,
    #[serde(rename = "listen_port")]
    pub listen_port: i64,
    #[serde(rename = "auth_enabled", default, skip_serializing_if = "Option::is_none")]
    pub auth_enabled: Option<bool>,
    #[serde(rename = "username", default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "upstream_id", default, skip_serializing_if = "Option::is_none")]
    pub upstream_id: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProxyUpstreamSpec {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "username", default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "enabled", default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProxyLifecycleCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    #[serde(rename = "action")]
    pub action: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProbeUpstreamProxyCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "upstream_id")]
    pub upstream_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RotateIpCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SwitchEsimProfileCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "modem_imei")]
    pub modem_imei: String,
    #[serde(rename = "target_iccid")]
    pub target_iccid: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateCardPolicyCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "policy_version")]
    pub policy_version: String,
    #[serde(rename = "policies")]
    pub policies: Vec<CardPolicy>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SubscriptionCapability {
    #[serde(rename = "sms_send", default, skip_serializing_if = "Option::is_none")]
    pub sms_send: Option<bool>,
    #[serde(rename = "sms_receive", default, skip_serializing_if = "Option::is_none")]
    pub sms_receive: Option<bool>,
    #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
    pub data: Option<bool>,
    #[serde(rename = "voice", default, skip_serializing_if = "Option::is_none")]
    pub voice: Option<bool>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CardPolicy {
    #[serde(rename = "iccid")]
    pub iccid: String,
    #[serde(rename = "cellular_enabled")]
    pub cellular_enabled: bool,
    #[serde(rename = "vertical")]
    pub vertical: String,
    #[serde(rename = "apn", default, skip_serializing_if = "Option::is_none")]
    pub apn: Option<String>,
    #[serde(rename = "capability", default, skip_serializing_if = "Option::is_none")]
    pub capability: Option<SubscriptionCapability>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateCapabilityMatrixCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "matrix_version")]
    pub matrix_version: String,
    #[serde(rename = "matrix_sha256")]
    pub matrix_sha256: String,
    #[serde(rename = "matrix")]
    pub matrix: ContextValue,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SelfUpdateCommand {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "signature")]
    pub signature: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolErrorPayload {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "related_message_id", default, skip_serializing_if = "Option::is_none")]
    pub related_message_id: Option<String>,
    #[serde(rename = "retryable")]
    pub retryable: bool,
    #[serde(rename = "retry_after_ms", default, skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", deny_unknown_fields)]
pub enum Command {
    SendSms {
        #[serde(rename = "to")]
        to: String,
        #[serde(rename = "body")]
        body: String,
        #[serde(rename = "modem_imei")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        modem_imei: Option<String>,
        #[serde(rename = "iccid")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        iccid: Option<String>,
    },
    RestartModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    SwitchEsimProfile {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "target_iccid")]
        target_iccid: String,
    },
    ListEsimProfiles {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    ReadEsimInfo {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    RetrieveEsimNotification {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "sequence_number")]
        sequence_number: i64,
    },
    InitiateEsimAuthentication {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "smdp_address")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        smdp_address: Option<String>,
    },
    DownloadEsimProfile {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "activation_code")]
        activation_code: String,
        #[serde(rename = "confirmation_code")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        confirmation_code: Option<String>,
    },
    RunAtCommand {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "command")]
        command: String,
        #[serde(rename = "timeout_ms")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        timeout_ms: Option<i64>,
        #[serde(rename = "force")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        force: Option<bool>,
    },
    SendUssd {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "code")]
        code: String,
        #[serde(rename = "stage")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        stage: Option<String>,
    },
    SetRadio {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "enabled")]
        enabled: bool,
    },
    ScanOperators {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    SelectOperator {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "mode")]
        mode: String,
        #[serde(rename = "plmn")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        plmn: Option<String>,
    },
    ModemReport {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    ResetModemUsb {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    SetDataNetwork {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "enabled")]
        enabled: bool,
    },
    ConfigureApn {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "cid")]
        cid: i64,
        #[serde(rename = "pdp_type")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pdp_type: Option<String>,
        #[serde(rename = "apn")]
        apn: String,
        #[serde(rename = "username")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        username: Option<String>,
        #[serde(rename = "password")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        password: Option<String>,
        #[serde(rename = "auth")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        auth: Option<String>,
    },
    SetUsbnetMode {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "mode")]
        mode: String,
    },
    ReregisterNetwork {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    RefreshModems,
    ReadLogs {
        #[serde(rename = "after")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        after: Option<i64>,
        #[serde(rename = "limit")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<i64>,
        #[serde(rename = "contains")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        contains: Option<String>,
    },
    ClaimModemCandidate {
        #[serde(rename = "candidate_key")]
        candidate_key: String,
    },
    RevokeModemCandidate {
        #[serde(rename = "candidate_key")]
        candidate_key: String,
    },
    RegisterModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "note")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        note: Option<String>,
    },
    CreateModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "family")]
        family: String,
        #[serde(rename = "note")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        note: Option<String>,
    },
    UnregisterModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    ReconfirmModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    UpdateModem {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "note")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        note: Option<String>,
    },
    RenameEsimProfile {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "iccid")]
        iccid: String,
        #[serde(rename = "nickname")]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        nickname: Option<String>,
    },
    DisableEsimProfile {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "iccid")]
        iccid: String,
    },
    DeleteEsimProfile {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
        #[serde(rename = "iccid")]
        iccid: String,
    },
    ConfigureProxy {
        #[serde(rename = "instances")]
        instances: Vec<ProxyInstanceSpec>,
        #[serde(rename = "upstreams")]
        upstreams: Vec<ProxyUpstreamSpec>,
    },
    ProxyLifecycle {
        #[serde(rename = "instance_id")]
        instance_id: String,
        #[serde(rename = "action")]
        action: String,
    },
    ProbeUpstreamProxy {
        #[serde(rename = "upstream_id")]
        upstream_id: String,
    },
    RotateIp {
        #[serde(rename = "modem_imei")]
        modem_imei: String,
    },
    UpdateCardPolicy {
        #[serde(rename = "policy_version")]
        policy_version: String,
        #[serde(rename = "policies")]
        policies: Vec<CardPolicy>,
    },
    UpdateCapabilityMatrix {
        #[serde(rename = "matrix_version")]
        matrix_version: String,
        #[serde(rename = "matrix_sha256")]
        matrix_sha256: String,
        #[serde(rename = "matrix")]
        matrix: ContextValue,
    },
    SelfUpdate {
        #[serde(rename = "version")]
        version: String,
        #[serde(rename = "url")]
        url: String,
        #[serde(rename = "sha256")]
        sha256: String,
        #[serde(rename = "signature")]
        signature: String,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Envelope {
    pub v: u8,
    pub kind: MessageKind,
    pub id: String,
    pub ts: i64,
    #[serde(rename = "device_id")]
    pub device_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none", with = "opt_u64_decimal")]
    pub seq: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "trace_id")]
    pub trace_id: Option<String>,
    pub payload: serde_json::Value,
}

impl Envelope {
    pub fn validate_sequence(&self) -> Result<(), String> {
        match (self.kind.is_sequenced(), self.seq) {
            (true, None) => Err(format!("{} requires seq", self.kind.as_str())),
            (false, Some(_)) => Err(format!("{} must not have seq", self.kind.as_str())),
            _ => Ok(()),
        }
    }
}
